import { db } from './db';
import { SearchService } from './SearchService';
import { createLogger } from '../utils/logger';

const log = createLogger('ContentSync');

// Category mapping from content.db categories to app stores
const CATEGORY_MAPPING = {
    // Health categories
    'Emergency First Aid': 'health',
    'Environmental Emergencies': 'health',
    'Trauma': 'health',
    'Medical Emergencies': 'health',
    'Medications': 'health',
    'Anatomy Reference': 'health',

    // Legal categories
    'Legal Rights UK': 'law',

    // Survival categories
    'Survival Skills': 'survival'
};

/**
 * Determine the target store category for an article based on its categories
 */
function determineCategory(articleCategories) {
    if (!articleCategories || !Array.isArray(articleCategories)) {
        return 'health'; // Default to health
    }

    for (const cat of articleCategories) {
        if (CATEGORY_MAPPING[cat]) {
            return CATEGORY_MAPPING[cat];
        }
    }

    // Fallback: check for keyword patterns
    const categoriesStr = articleCategories.join(' ').toLowerCase();
    if (categoriesStr.includes('legal') || categoriesStr.includes('rights') || categoriesStr.includes('law')) {
        return 'law';
    }
    if (categoriesStr.includes('survival') || categoriesStr.includes('flood') || categoriesStr.includes('shelter')) {
        return 'survival';
    }

    return 'health'; // Default
}

/**
 * Syncs articles from content.db (SQLite) to IndexedDB stores
 * This bridges the build-time content pipeline with runtime storage
 */
export const contentSync = {
    /**
     * Sync articles from bundled content.db to IndexedDB
     * For web: reads from public/assets/content-manifest.json
     * For native: reads from SQLite directly
     */
    async syncContentToIndexedDB() {
        try {
            // Check if already synced by checking multiple stores
            const [healthContent, lawContent, survivalContent] = await Promise.all([
                db.getAll('health_content').catch(() => []),
                db.getAll('law_content').catch(() => []),
                db.getAll('survival_content').catch(() => [])
            ]);

            const totalExisting = healthContent.length + lawContent.length + survivalContent.length;
            if (totalExisting > 0) {
                log.info(`Content already synced: ${totalExisting} articles`);
                return {
                    synced: false,
                    reason: 'already_synced',
                    count: totalExisting,
                    breakdown: {
                        health: healthContent.length,
                        law: lawContent.length,
                        survival: survivalContent.length
                    }
                };
            }

            // Try to load content manifest JSON (generated by export-content-json.js)
            log.info('Attempting to load content manifest...');

            // Try minified version first (smaller), then full version
            const manifestUrls = [
                '/assets/content-manifest.min.json',
                '/assets/content-manifest.json'
            ];

            for (const url of manifestUrls) {
                try {
                    const response = await fetch(url);
                    if (response.ok) {
                        log.info(`Loading manifest from ${url}`);
                        const manifest = await response.json();
                        return await this.syncFromManifest(manifest);
                    }
                } catch (_fetchError) {
                    log.debug(`Manifest not found at ${url}`);
                }
            }

            log.warn('No content manifest found - app will run without reference content');
            return { synced: false, reason: 'no_content_source' };
        } catch (error) {
            log.error('Content sync failed', error);
            return { synced: false, reason: 'error', error: error.message };
        }
    },

    /**
     * Sync from a content manifest JSON file
     */
    async syncFromManifest(manifest) {
        const counts = { health: 0, law: 0, survival: 0 };
        const errors = [];

        if (!manifest.articles || !Array.isArray(manifest.articles)) {
            log.warn('Manifest has no articles array');
            return { synced: false, reason: 'invalid_manifest' };
        }

        log.info(`Syncing ${manifest.articles.length} articles from manifest...`);

        for (const article of manifest.articles) {
            try {
                // Determine category based on article metadata
                const category = determineCategory(article.categories);

                // Create summary from plain text (first 300 chars, ending at word boundary)
                let summary = '';
                if (article.body_plain) {
                    summary = article.body_plain.substring(0, 300);
                    const lastSpace = summary.lastIndexOf(' ');
                    if (lastSpace > 200) {
                        summary = summary.substring(0, lastSpace) + '...';
                    }
                }

                // Store in appropriate IndexedDB store
                const contentData = {
                    id: article.slug,
                    title: article.title,
                    summary: summary,
                    content: article.body_html || '',
                    source: article.source || 'wikipedia',
                    source_url: article.source_url || '',
                    categories: article.categories || [],
                    importedAt: new Date().toISOString()
                };

                if (category === 'health') {
                    await db.put('health_content', contentData);
                    counts.health++;
                } else if (category === 'law') {
                    await db.put('law_content', {
                        ...contentData,
                        fullText: article.body_plain || ''
                    });
                    counts.law++;
                } else if (category === 'survival') {
                    await db.put('survival_content', {
                        ...contentData,
                        searchableText: article.body_plain || '',
                        description: summary
                    });
                    counts.survival++;
                }

                // Index for search
                await SearchService.addDocument({
                    id: article.slug,
                    slug: article.slug,
                    title: article.title,
                    content: article.body_plain || '',
                    description: summary,
                    category: category
                });
            } catch (error) {
                log.warn(`Failed to sync article: ${article.title}`, error);
                errors.push({ title: article.title, error: error.message });
            }
        }

        const totalSynced = counts.health + counts.law + counts.survival;
        log.info(`Content sync complete: ${totalSynced} articles`);
        log.info(`  Health: ${counts.health}, Law: ${counts.law}, Survival: ${counts.survival}`);

        if (errors.length > 0) {
            log.warn(`${errors.length} articles failed to sync`);
        }

        return {
            synced: true,
            count: totalSynced,
            breakdown: counts,
            errors: errors.length > 0 ? errors : undefined
        };
    },

    /**
     * Force re-sync by clearing existing content first
     */
    async forceSyncContent() {
        log.info('Force syncing content - clearing existing...');

        // Clear existing content
        await Promise.all([
            db.clear('health_content').catch(() => {}),
            db.clear('law_content').catch(() => {}),
            db.clear('survival_content').catch(() => {}),
            db.clear('search_index').catch(() => {})
        ]);

        // Rebuild search index
        await SearchService.rebuildIndex();

        // Now sync
        return await this.syncContentToIndexedDB();
    },

    /**
     * Get sync status
     */
    async getSyncStatus() {
        const [healthContent, lawContent, survivalContent] = await Promise.all([
            db.getAll('health_content').catch(() => []),
            db.getAll('law_content').catch(() => []),
            db.getAll('survival_content').catch(() => [])
        ]);

        return {
            synced: healthContent.length + lawContent.length + survivalContent.length > 0,
            breakdown: {
                health: healthContent.length,
                law: lawContent.length,
                survival: survivalContent.length
            },
            total: healthContent.length + lawContent.length + survivalContent.length
        };
    }
};
